name: "Validate PRs for Main and Dev"

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Create temporary .sln from .slnx
        run: |
          dotnet new sln -n Mottu
          find . -name "*.csproj" -exec dotnet sln Mottu.sln add {} \;

      - name: Restore dependencies
        run: dotnet restore *.sln

      - name: Build solution
        run: dotnet build *.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test *.sln --no-build --configuration Release --verbosity normal
